version: '3.9'

services:
  backend:
    image: backend
    build:
      context: app
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --reload       
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@localhost:5432/postgres
    
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: yourpostgresdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      
volumes:
  postgres-data:
